server:
  port: 6666



provider:
  service:
    name: producer-hello


#producer-hello:
#  ribbon:
#    listOfServers:
#      - http://localhost:4444
#      - http://localhost:4443
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: consumer-hello-ribbon
