server:
  port: 3333

eureka:
  client:
    service-url:
      # 指定注册中心地址
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true #这个属性不会提示 修改健康检测方式为health监控

  instance:
    # 修改服务的实例名和端口
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true


spring:
  application:
    name: eureka-client


# actuator设置

management:
  endpoints:
    web:
      exposure:
        # 暴露所有断定 默认是info 和 health
        include: "*"
  endpoint:
    health:
      # 默认是never
      show-details: always